name: test-server-csv-deploy-pipeline

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: s3 deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AKID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DDB_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: aws s3 sync . s3://${{ secrets.TEST_S3_BUCKET_NAME }} --delete --exclude ".git*" 

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.GITHUB_ACCESS_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/adelie-penguin-sw/Intelligence-Server/actions/workflows/deploy.yml/dispatches \
          -d '{"ref": "dev"}'