name: test-server-csv-deploy-pipeline

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: s3 deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_AKID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DDB_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: aws s3 sync . s3://${{ secrets.TEST_S3_BUCKET_NAME }} --delete --exclude ".git*"